name: Flutter CI (APK Build)

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: "Build type (release/debug)"
        required: false
        default: "release"

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Build APK
        run: |
          if [ "${{ github.event.inputs.build_type }}" = "debug" ]; then
            flutter build apk --debug
          else
            flutter build apk --release
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ github.event.inputs.build_type }}-apk
          path: build/app/outputs/flutter-apk/*.apk
          retention-days: 7
