name: Deploy Flutter Web to Vercel

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Flutter packages
        run: flutter pub get

      - name: Enable Flutter web support
        run: flutter create . --platforms web

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Deploy to Vercel
        run: |
          npm i -g vercel@latest
          vercel pull --yes --environment=production --token ${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prod ./build/web --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
